FLP-578 ReadMe
SkillsFundingAgency/das-funding-apprenticeship-payments pull request #34
Opened 2024-04-15 15:29 UTC by MikeV-TalentConsulting

2024-04-16 08:52 UTC, tom-gough requested changes

2024-04-16 08:56 UTC, MikeV-TalentConsulting commented on README.md
> +Most of the application configuration is taken from the [das-employer-config repository](https://github.com/SkillsFundingAgency/das-employer-config) and the default values can be used in most cases.
Fixed

2024-04-16 08:58 UTC, tom-gough approved these changes

2024-04-23 14:34 UTC, tom-gough approved these changes

2024-04-26 13:25 UTC, merged