Flp 237 rollup payments
SkillsFundingAgency/das-funding-apprenticeship-payments pull request #5
Opened 2023-04-03 19:48 UTC by MichaelYoung1981

2023-04-05 09:19 UTC, tom-gough requested changes

2023-04-05 09:19 UTC, tom-gough commented on src/Domain/Apprenticeship/Apprenticeship.cs
> +            var censusDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1).AddMonths(1).AddDays(-1);
Is this logic covered in a unit test?

2023-04-05 10:23 UTC, tom-gough approved these changes

2023-04-18 12:09 UTC, tom-gough submitted a review, later dismissed

2023-04-19 08:12 UTC, dinathain approved these changes

2023-04-19 08:33 UTC, merged